spring.application.name=airBnb

spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username:postgres
spring.datasource.password:newpassword123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

